/**
 * achievements.js — достижения.
 * condition(state, stats) -> true | число (для прогресса 0..1 считается в системе).
 * bonus — необязательный пассивный бонус (учитывается в economy через count достижений,
 * а спец-бонусы применяются явно по id).
 */

export const ACHIEVEMENTS = [
  { id: "first_commit", name: "First Commit", icon: "🌱", desc: "Сделать первый коммит.",
    check: (s) => s.stats.clicks.manual >= 1 },
  { id: "clicks_100", name: "Carpal Tunnel Preview", icon: "🖱️", desc: "100 ручных кликов.",
    check: (s) => s.stats.clicks.manual >= 100, progress: (s) => s.stats.clicks.manual / 100 },
  { id: "clicks_1000", name: "Keyboard Warrior", icon: "⚔️", desc: "1000 ручных кликов.",
    check: (s) => s.stats.clicks.manual >= 1000, progress: (s) => s.stats.clicks.manual / 1000 },
  { id: "clicks_10000", name: "Human Autoclicker", icon: "🤡", desc: "10 000 ручных кликов.",
    check: (s) => s.stats.clicks.manual >= 10000, progress: (s) => s.stats.clicks.manual / 10000 },
  { id: "automation_begins", name: "Automation Begins", icon: "🔁", desc: "Купить первый генератор.",
    check: (s) => Object.values(s.buildings).some((n) => n > 0) },
  { id: "dockerized", name: "Dockerized", icon: "🐳", desc: "10 Docker Container в строю.",
    check: (s) => (s.buildings.docker ?? 0) >= 10, progress: (s) => (s.buildings.docker ?? 0) / 10 },
  { id: "k8s_master", name: "Kubernetes Master", icon: "☸️", desc: "25 Kubernetes Pod.",
    check: (s) => (s.buildings.k8s_pod ?? 0) >= 25, progress: (s) => (s.buildings.k8s_pod ?? 0) / 25 },
  { id: "no_downtime", name: "No Downtime", icon: "9️⃣💯", desc: "Достичь 1000 CPS.",
    check: (s) => s.derived.cps >= 1000, progress: (s) => s.derived.cps / 1000 },
  { id: "million_commits", name: "1 Million Commits", icon: "💎", desc: "1 млн коммитов за игру.",
    check: (s) => s.resources.lifetimeCommits >= 1e6, progress: (s) => s.resources.lifetimeCommits / 1e6 },
  { id: "billion_commits", name: "Billion Line Legacy", icon: "🦖", desc: "1 млрд коммитов за игру.",
    check: (s) => s.resources.lifetimeCommits >= 1e9, progress: (s) => s.resources.lifetimeCommits / 1e9 },
  { id: "cloud_native", name: "Cloud Native", icon: "☁️", desc: "Владеть по одному Serverless, CDN и LB.",
    check: (s) => (s.buildings.serverless ?? 0) >= 1 && (s.buildings.cdn ?? 0) >= 1 && (s.buildings.lb ?? 0) >= 1 },
  { id: "prod_hero", name: "Production Hero", icon: "🦸", desc: "Пережить инцидент и не потерять прод.",
    check: (s) => s.stats.events.resolvedIncidents >= 1 },
  { id: "sre_nightmare", name: "SRE Nightmare", icon: "😱", desc: "Получить 10 инцидентов.",
    check: (s) => s.stats.events.incidents >= 10, progress: (s) => s.stats.events.incidents / 10 },
  { id: "chaos_coordinator", name: "Chaos Coordinator", icon: "🎪", desc: "30 случайных событий произошло.",
    check: (s) => s.stats.events.total >= 30, progress: (s) => s.stats.events.total / 30 },
  { id: "offline_warrior", name: "Offline Warrior", icon: "🛌", desc: "Заработать 100k коммитов офлайном.",
    check: (s) => s.stats.offlineEarnedTotal >= 100_000, progress: (s) => s.stats.offlineEarnedTotal / 100_000 },
  { id: "prestige_beginner", name: "Migration Complete", icon: "🚀", desc: "Совершить первый престиж.",
    check: (s) => s.stats.prestige.count >= 1 },
  { id: "certified", name: "AWS Certified (x3)", icon: "📜", desc: "Накопить 50 Cloud Tokens.",
    check: (s) => s.resources.prestigeTokens >= 50, progress: (s) => s.resources.prestigeTokens / 50 },
  { id: "upgrade_hoarder", name: "Extension Hoarder", icon: "🧩", desc: "Купить 15 улучшений.",
    check: (s) => Object.keys(s.upgrades).length >= 15, progress: (s) => Object.keys(s.upgrades).length / 15 },
  { id: "full_team", name: "DevOps Department", icon: "🏢", desc: "Владеть по 50 Junior Developer.",
    check: (s) => (s.buildings.junior ?? 0) >= 50, progress: (s) => (s.buildings.junior ?? 0) / 50 },
  { id: "devops_legend", name: "DevOps Legend", icon: "👑", desc: "Достичь 1 трлн lifetime commits.",
    check: (s) => s.resources.lifetimeCommits >= 1e12, progress: (s) => s.resources.lifetimeCommits / 1e12 },
];
